name: Check Pull Request
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
  merge_group:

jobs:
  check-title:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: pnpm/action-setup@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          check-latest: true
          cache: "pnpm"
      - run: pnpm install
      - name: Check title
        run: |
          title="${{ github.event.pull_request.title }}"
          title_escaped=${title//\'/\'}
          if [ "$title" == "feat: update generated APIs" ]; then
            echo "Invalid title."
            exit 1
          else
            echo "$title_escaped" | pnpm commitlint
          fi
