name: Check Pull Request
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

jobs:
  check-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.3.1
      - uses: pnpm/action-setup@v4.1.0
      - name: Use Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 20.19.6
          check-latest: true
          cache: 'pnpm'
      - run: make install-dependencies
      - name: Check title
        run: |
          title=$(cat <<- "EOF"
          ${{ github.event.pull_request.title }}
          EOF
          )
          if [ "$title" == "feat: update generated APIs" ]; then
            echo "Invalid title."
            exit 1
          else
            echo "$title" | pnpm commitlint
          fi
