name: Check Pull Request
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

jobs:
  check-title:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 20.20.0
          check-latest: true
          cache: 'pnpm'
      - run: make install-dependencies
      - name: Check title
        run: |
          title=$(cat <<- "EOF"
          ${{ github.event.pull_request.title }}
          EOF
          )
          if [ "$title" == "feat: update generated APIs" ]; then
            echo "Invalid title."
            exit 1
          else
            echo "$title" | pnpm commitlint
          fi
